config/routes.rb
Rails.application.routes.draw do
  get 'new/create'
  root 'registrations#new'
  resources 'creations', only: [:new, :create]
  resources 'registrations', only: [:new, :create] do
     resources 'gossips', only: [:new, :create, :show, :index, :edit, :update, :destroy] do 
        resources 'comments', only: [:new, :create, :show, :edit, :update, :destroy, :show] 
        resources 'likes', only: [:new, :create, :show, :edit, :update, :destroy, :show]
     end 
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user	
  has_many :likes, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/registration.rb
class Registration < ApplicationRecord
  def check(registration)
    if User.find_by(email: "#{registration.email}") == nil
      return false 
    end 
    if registration.password == User.find_by(email: "#{registration.email}").password
      return true
    end
    return false
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes
  has_many :gossips
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def edit
    @registration = Registration.find(params[:registration_id])
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
  end

  def new
    @registration = Registration.find(params[:registration_id])
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.new
  end

  def create
    tmp = params[:format].split('/')
    if tmp[1] == "Gossip"
      @comment = Comment.create!(content: params_from_form[:content], user_id: params[:registration_id].to_i, commentable_type: "Gossip", commentable_id: params[:gossip_id] )
    else
      @comment = Comment.create!(content: params_from_form[:content], user_id: params[:registration_id].to_i, commentable_type: "Comment", commentable_id: tmp[0].to_i)
    end
    redirect_to registration_gossips_path(params[:registration_id])
  end 

  def update
    @comment = Comment.find(params[:id])
  	@comment.update(params_from_form)
    redirect_to registration_gossips_path(params[:registration_id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to registration_gossips_path(params[:registration_id])
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private 
  def params_from_form
    params.require(:comment).permit(:content)
  end
  def params_from_form_format
    params.require(:comment).permit(:format)
  end

end

app/controllers/creations_controller.rb
class CreationsController < ApplicationController
  def new
  end
  
  def create
    User.create!(creation_params)
    redirect_to root_path
  end
  
  private

  def creation_params
    params.permit(:email, :password, :first_name, :last_name, :description)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
 	
 	def new
    @registration = Registration.find(params[:registration_id])
  	@gossip = Gossip.new
  end

  def create
  	@gossip = Gossip.create!(content: params_from_form[:content], user_id: params[:registration_id].to_i)
    redirect_to registration_gossips_path(params[:registration_id])
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = Gossip.find(params[:id]).comments
  end

  def index
    @gossip = Gossip.all
  end

  def edit
    @registration = Registration.find(params[:registration_id])
    @gossip = Gossip.find(params[:id])
  end

  def update
  	@gossip = Gossip.find(params[:id])
  	@gossip.update(params_from_form)
    redirect_to registration_gossips_path(params[:registration_id])
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to registration_gossips_path(params[:registration_id])
  end

  private

  def params_from_form
    params.require(:gossip).permit(:content)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
  end

  def create
    @likes = Like.create!(user_id: User.find(params[:registration_id]).id, gossip_id: params[:gossip_id])
    redirect_to registration_gossip_path(params[:registration_id], params[:gossip_id])
  end

  def destroy
    @likes = Like.find(params[:id])
    @likes.destroy
    redirect_to registration_gossip_path(params[:registration_id], params[:gossip_id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @registration =  Registration.new
  end

  def create
    @registration = Registration.create(registration_params)
    instance_checking = Registration.new 
    if instance_checking.check(@registration)
      redirect_to registration_gossips_path(User.find_by(email: "#{@registration.email}").id)
    else
      redirect_to 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
    end
  end

  private
  def registration_params
    params.require(:registration).permit(:email, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/creations_helper.rb
module CreationsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Des regrets sur ce commentaire ? </h1>

<%= form_for [@registration, @gossip, @comment] do |f| %>

  <div class="form-group">		
    <label for="formGroupExampleInput">Modifie moi ça :</label>
    <%= f.text_area :content, class: "form-control" %>
  </div>

    <%= f.submit "Update ton Commentaire !", class: "btn btn-success" %>


    <%= link_to "Supprimer le Commentaire", registration_gossip_comment_path(params[:registration_id], params[:gossip_id], @comment.id), class: "btn btn-danger", method: :delete %>



<% end %>

app/views/comments/new.html.erb
<h1>Ajouter un commentaire</h1>


<%= form_for [@registration, @gossip, @comment] do |f| %>
  <div class="form-group">		
    <label for="formGroupExampleInput">Ajoute moi du commentaire bien sale :</label>
    <%= f.text_area :content, class: "form-control" %>
    <%=hidden_field_tag :format, params[:format]%> 
  </div>
    <%= f.submit "Enregistre ton commentaire !", class: "btn btn-success" %>

<% end %>
</div>

app/views/comments/show.html.erb
<h1>Commentaire</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/creations/create.html.erb
<h1>Creations#create</h1>
<p>Find me in app/views/creations/create.html.erb</p>

app/views/creations/new.html.erb
<h1>Incriptez vous</h1>
	
<%= form_tag creations_path, method: :post do%>
	<div class="form-group">		
		<%= label_tag 'Email:' %>
		<%= text_field_tag 'email', '', placeholder: 'Your username...', class: "form-control", id: "formGroupExampleInput2" %>
	</div>	
	<div class="form-group">	
		<%= label_tag 'Mot de passe:' %>
		<%= text_field_tag 'password', '', placeholder: 'Your username...', class: "form-control", id: "formGroupExampleInput2" %>
	</div>
	<div class="form-group">
		<%= label_tag 'Prénom:' %>
		<%= text_field_tag 'first_name', '', placeholder: 'Your username...', class: "form-control", id: "formGroupExampleInput2" %>
	</div>
	<div class="form-group">
		<%= label_tag 'Nom:' %>
		<%= text_field_tag 'last_name', '', placeholder: 'Your username...', class: "form-control", id: "formGroupExampleInput2" %>
	</div>
	<div class="form-group">		
		<%= label_tag 'Bio:' %>
		<%= text_field_tag 'description', '', placeholder: 'Your username...', class: "form-control", id: "formGroupExampleInput2" %>
	</div>
		<%= submit_tag "Inscription", name: nil, class: "btn btn-success" %>
<% end %>

app/views/gossips/edit.html.erb
<div style="margin-left: 100px; margin-top: 100px; width: 30%;">
	<h1>Editer le Gossip numéro <%= @gossip.id %> :</h1>


	<%= form_for [@registration, @gossip] do |f| %>

		<div class="form-group">		
			<label for="formGroupExampleInput">Ajoute moi du gros gossip :</label>
			<%= f.text_area :content, class: "form-control" %>
		</div>

			<%= f.submit "Update ton Gossip !", class: "btn btn-success" %>

	<% end %>

</div>

app/views/gossips/index.html.erb
<div style="margin-left: 100px; margin-top: 100px; width: 30%;">
	<h1>Voici la liste des Gossips</h1>
	<hr />

	
	<table class="table table-hover">
  	<thead>
    	<tr>
     	 <th>ID</th>
     	 <th>Anonymous Gossipeur</th>
     	 <th>Lien vers le Gossip</th>
    	</tr>
  	</thead>
  	<tbody>
			<% @gossip.each do |element| %>
				<tr>
					<td>
						<%= element.id %>
					</td>
					<td>
						<%= element.user.first_name %>
					</td>
					<td>

						<%= link_to "Lien", registration_gossip_path(params[:registration_id], element.id) %>	
					</td>
				</tr>
			<% end %>
  	</tbody>
	</table>


</div>

app/views/gossips/new.html.erb
<div style="margin-left: 100px; margin-top: 100px; width: 30%;">
	<h1>Ajouter un Fu***** Gossip</h1>


	<%= form_for [@registration, @gossip] do |f| %>
		<div class="form-group">		
			<label for="formGroupExampleInput">Ajoute moi du gros gossip :</label>
      <%= f.text_area :content, class: "form-control" %>

		</div>
			<%= f.submit "Enregistre ton Gossip !", class: "btn btn-success" %>

	<% end %>
</div>

app/views/gossips/show.html.erb
<div style="margin-left: 100px; margin-top: 100px; width: 30%;">
	<h1>Voici le gossip numéro <%= @gossip.id %> !</h1>
	<hr />
	<blockquote class="blockquote">
	 <p class="mb-0"><%= @gossip.content %></p>
 	<footer class="blockquote-footer"><%= @gossip.user.first_name %></footer>
	</blockquote>
	<% if @gossip.user_id == params[:registration_id].to_i %>
		<%= link_to "Editer le Gossip", edit_registration_gossip_path(params[:registration_id], @gossip.id), class: "btn btn-success" %>
		<%= link_to "Supprimer le Gossip", registration_gossip_path(params[:registration_id], @gossip.id), class: "btn btn-danger", method: :delete %>
	<% end %>
  <hr />

  <%= "#{@gossip.likes.count.to_s} likes" %>
	<br />
	<% if @gossip.likes.find_by(user_id: User.find(params[:registration_id])) == nil  %>
		<%= link_to "Like", registration_gossip_likes_path(params[:registration_id], @gossip.id), class: "btn btn-danger", method: :post  %>
	<% else %>
    		<%= link_to "Unlike", registration_gossip_like_path(params[:registration_id], @gossip.id, @gossip.likes.find_by(user_id: User.find(params[:registration_id])).id), method: :delete %>
  	<% end %>
  
  <br />
  <br />
  <%= link_to "Commenter le Gossip", new_registration_gossip_comment_path(params[:registration_id],params[:id], "Gossip" ), class: "btn btn-success" %> <br/ >
	<br />
  <%= "#{@gossip.comments.count.to_s} comments" %> 
  <br />
  <br />

	<table class="table table-hover">
  <thead>
    <tr>
      <th>Commentaire</th>
      <th>Auteur</th> 
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |element| %>
      	<tr>
        	<td>
          	<%= element.content %>
	        </td>
        	<td>
 	         <%= element.user.first_name %>
        	</td>
        	<td>
          	<% if params[:registration_id].to_i == element.user_id %>
          		<%= link_to "Éditer", edit_registration_gossip_comment_path(params[:registration_id], params[:id], element.id) %>	
          	<% end %>
        	</td>
		<td>
			<%= link_to "Commenter le commentaire", new_registration_gossip_comment_path(params[:registration_id], params[:id], [element.id, "Comment"]), class: "btn btn-success" %>
		<br/ >
		</td>
	</tr>
		<% Comment.all.each do |sub| %>
			<% if sub.commentable_type == "Comment" && sub.commentable_id == element.id %>
				<tr>
					<td>
					</td>
					<td>
						<%= sub.content %>
					</td>
					<td>
						<%= sub.user.first_name %>
					</td>
					<td>
						<% if params[:registration_id].to_i == element.user_id %>
							<%= link_to "Éditer", edit_registration_gossip_comment_path(params[:registration_id], params[:id], sub.id) %>
						<% end %>
					</td>
				</tr>
			<% end %>
		<% end %>
    <% end %>
  </tbody>
</table>

 <hr />

	<%= link_to "Voir tous les gossips", registration_gossips_path(params[:registration_id]) %>

</div>

app/views/layouts/_header.html.erb
<header>



	<nav class="navbar navbar-inverse navbar-fixed-top">
  	<div class="container-fluid">
    	<div class="navbar-header">
    	  <a class="navbar-brand" href="/">The Gossip Project</a>
    	</div>
      <ul class="nav navbar-nav">
      <% if params[:registration_id] %>
        <li><%= link_to "Créer un gossip", new_registration_gossip_path(params[:registration_id]) %></li>
        <li><%= link_to "Liste de tous les Gossips", registration_gossips_path(params[:registration_id]) %></li>
	<% else %>
	<li><%= link_to "Créer un utilisateur", new_creation_path %></li>
	</ul>
  	</div>
  </nav>
  
<% end %>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>

  <body>
    <!-- En gros, on fait appel à "_header.html.erb" -->
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/delete.html.erb
<h1>Likes#delete</h1>
<p>Find me in app/views/likes/delete.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron" style="padding-left: 30px;">
  <h1>Bienvenue Moussaillon !</h1>
  <i>(ou Corsaire ou même peut-être rénégat)</i>
  <h3>
    Ici, tu peux retrouver les Gossips des mousaillons 🎓
  </h3>
  <%= link_to "Voir tous les gossips !", gossips_path, class: "btn btn-lg btn-primary" %>
</div>